"""
Counterfactual Scenario Engine — Blix v0.3.11  (New module 9, Phase 4)

Per explicit design direction, this single module REPLACES the
originally-separate "Imagination Engine" and "Scenario Tree Search"
ideas — they were redundant as proposed. One lightweight pipeline:

    Current state
      ↓
    Alternative actions
      ↓
    Top-K futures
      ↓
    Value network
      ↓
    Ranked scenarios

This wraps existing v0.3.10 infrastructure
(``world_model.scenario_ranker.ScenarioRanker``,
``world_model.value_network.ValueNetwork``) rather than building new
simulation machinery. Explicit non-goals, matching the scope-reduction
constraint: no MCTS, no tree search beyond one flat top-K ranking pass,
no deep multi-step rollout/simulation, no world-model-driven future
generation — alternatives are supplied by the caller (e.g. candidate
``ReasoningStrategy`` values, candidate next actions), not generated by
exploring a simulated environment.

== THE safeguard ==
This module does not import ``memory.beliefs`` AT ALL — there is no
``BeliefStore`` reference anywhere in this file, by design, so a
counterfactual scenario CANNOT reach the belief system even by
accident. Every output here carries ``EpistemicStatus.COUNTERFACTUAL``,
``confidence``, ``evidence_count`` (always 0 — a counterfactual has, by
definition, no direct observational evidence of its own; it's an
estimate FROM evidence about other things), ``basis``, and the
explicit field ``validated_causally=False``. If a counterfactual later
proves out, promoting it toward a trusted belief requires a human or
calling code to explicitly invoke
``memory.beliefs.BeliefStore.add_hypothesis()`` and, after real
confirming observation, ``confirm_observation()`` — two separate,
deliberate calls that live entirely outside this module.

Python 3.10 compatible.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from causality.epistemic_status import EpistemicStatus
from simulation.trajectory_graph import Trajectory, TrajectoryBuilder
from world_model.latent_world_model import LatentState
from world_model.scenario_ranker import RankedScenario, Scenario, ScenarioRanker
from world_model.value_network import ValueNetwork
from utils.logger import get_logger

log = get_logger(__name__)


@dataclass
class CounterfactualAlternative:
    """One 'what if' alternative action/strategy to evaluate against the current state."""

    name: str
    description: str
    resulting_state: LatentState


@dataclass
class CounterfactualResult:
    """
    One ranked counterfactual scenario estimate. Every field needed to
    keep this from being mistaken for a real observation is present
    and explicit, not just documented.
    """

    name: str
    description: str
    estimated_value: float
    confidence: float
    evidence_count: int = 0
    basis: str = ""
    epistemic_status: EpistemicStatus = EpistemicStatus.COUNTERFACTUAL
    validated_causally: bool = False
    trajectory: Optional["Trajectory"] = None   # v0.3.12 — populated by explore_with_trajectories()
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_dict(self) -> dict:
        return {
            "name": self.name, "description": self.description,
            "estimated_value": round(self.estimated_value, 4), "confidence": round(self.confidence, 4),
            "evidence_count": self.evidence_count, "basis": self.basis,
            "epistemic_status": self.epistemic_status.value, "validated_causally": self.validated_causally,
            "trajectory": self.trajectory.to_dict() if self.trajectory is not None else None,
            "generated_at": self.generated_at,
        }


class CounterfactualScenarioEngine:
    """
    Lightweight what-if scenario generation and ranking: current state
    -> alternative actions -> top-K futures -> value network -> ranked
    scenarios. No MCTS, no simulation, no world-model rollout.

    Parameters
    ----------
    value_network:
        ``ValueNetwork`` (v0.3.10) — supplies the value estimate behind
        every ranked scenario. Confidence in the resulting
        ``CounterfactualResult`` is derived from whether this network
        is trained or still cold-starting (an honest "how much should
        you trust this number" signal).
    scenario_ranker:
        Optional ``ScenarioRanker`` — reused rather than reimplemented
        if the caller already has one configured.
    """

    def __init__(self, value_network: ValueNetwork, scenario_ranker: Optional[ScenarioRanker] = None) -> None:
        self._value_network = value_network
        self._ranker = scenario_ranker or ScenarioRanker(value_network=value_network)

    # ------------------------------------------------------------------
    # Counterfactual generation + ranking
    # ------------------------------------------------------------------

    def explore(
        self, current_state: LatentState, alternatives: list[CounterfactualAlternative], top_k: int = 5,
    ) -> list[CounterfactualResult]:
        """
        Rank ``alternatives`` (each an already-specified "what if I did
        X instead" resulting state) by estimated value, returning the
        top ``top_k`` as explicit ``CounterfactualResult`` objects.

        ``alternatives`` must be supplied by the caller — this method
        does not generate its own candidate actions or simulate a
        world model forward; that's the explicit scope boundary for
        this release.
        """
        if not alternatives:
            return []

        scenarios = [Scenario(name=a.name, description=a.description, state=a.resulting_state) for a in alternatives]
        ranked = self._ranker.rank(scenarios)

        # Confidence in a counterfactual estimate is itself honest about
        # the underlying value network's training state — an untrained
        # network's "ranking" is much less trustworthy than a trained one's.
        base_confidence = 0.6 if self._value_network.is_trained else 0.25
        basis = (
            f"ScenarioRanker + ValueNetwork estimate (value_network.is_trained={self._value_network.is_trained}, "
            f"sample_count={self._value_network.sample_count})"
        )

        results = [
            CounterfactualResult(
                name=r.scenario.name, description=r.scenario.description, estimated_value=r.value,
                confidence=base_confidence, evidence_count=0, basis=basis,
            )
            for r in ranked[:top_k]
        ]
        return results

    def best(self, current_state: LatentState, alternatives: list[CounterfactualAlternative]) -> Optional[CounterfactualResult]:
        """Convenience: return only the single best-ranked counterfactual."""
        results = self.explore(current_state, alternatives, top_k=1)
        return results[0] if results else None

    # ------------------------------------------------------------------
    # v0.3.12 — full Scenario(actions, predicted_outcome, confidence, trajectory)
    # ------------------------------------------------------------------

    def explore_with_trajectories(
        self, current_state: LatentState, alternatives: list[CounterfactualAlternative], top_k: int = 5,
    ) -> list[CounterfactualResult]:
        """
        Same ranking as ``explore()``, but each returned
        ``CounterfactualResult`` additionally carries a
        ``simulation.trajectory_graph.Trajectory`` — a first-class
        ``current_state -> action -> resulting_state`` chain — in its
        ``trajectory`` field, matching the v0.3.12 spec's
        ``Scenario(actions, predicted_outcome, confidence, trajectory)``
        shape. Each counterfactual alternative is inherently a
        single-step trajectory (depth 1); for multi-step lookahead, use
        ``planning.beam_search.BeamSearchPlanner`` instead.

        Note: returns fresh ``CounterfactualResult`` objects — does not
        mutate the results from ``explore()``.
        """
        import copy
        base_results = self.explore(current_state, alternatives, top_k=top_k)
        by_name = {a.name: a for a in alternatives}

        enriched = []
        for result in base_results:
            alt = by_name.get(result.name)
            # Always create a shallow copy so we never mutate the shared explore() result
            result_copy = copy.copy(result)
            if alt is None:
                enriched.append(result_copy)
                continue
            builder = TrajectoryBuilder(current_state, epistemic_status=EpistemicStatus.COUNTERFACTUAL)
            builder.step(alt.name, alt.resulting_state, predicted_value_delta=result_copy.estimated_value, label=alt.description)
            result_copy.trajectory = builder.build()
            enriched.append(result_copy)
        return enriched
