"""
Pydantic schema for the persistent user profile — Python 3.10 compatible.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class Profile(BaseModel):
    """
    Long-lived personal context injected into every prompt.

    All fields are mutable; the profile grows as the user shares more
    information over time.

    Attributes
    ----------
    name:
        How the user wants to be addressed.
    education:
        Current or most recent educational context.
    interests:
        Broad topic areas the user cares about.
    projects:
        Active or recent projects Blix should be aware of.
    goals:
        Longer-horizon ambitions that shape tutoring direction.
    notes:
        Freeform additional context; reserved for future auto-update by
        the tutor agent (v2) without cluttering the typed fields.
    """

    name: str = Field(default="", description="User's preferred name.")
    education: str = Field(default="", description="Education level / institution.")
    interests: list[str] = Field(default_factory=list)
    projects: list[str] = Field(default_factory=list)
    goals: list[str] = Field(default_factory=list)

    # v2 extension point — auto-generated by the tutor agent
    notes: list[str] = Field(default_factory=list, description="Auto-generated profile notes (future).")

    def is_empty(self) -> bool:
        """Return ``True`` when no meaningful profile data has been set."""
        return not any([self.name, self.education, self.interests, self.projects, self.goals])
